### ISSUE TITLE
Sense

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/roBrowserLegacy#117]
Basic window implemented but sprite and monster name is missing

**Comment by alisonrag** [comment]
@MrAntares 
already fixed:
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/2f2037b3-d12d-4dcc-99a2-4a1ed8d59f69)

**Comment by MrAntares** [comment]
Fixed in https://github.com/MrAntares/roBrowserLegacy/commit/5020aec80d7eafa0109ef6a197d2440c077aadfa
