### ISSUE TITLE
Enemy Guild Emblem missing on WoE(GvG) Maps

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#124]
**Missing feature**
Guild Emblem on top of enemy player's head is missing on Browser.

**Screenshots (if applicable)**
Should look like this sitting/standing. It's not displayed on the browser.
![image](https://user-images.githubusercontent.com/214579/197106352-bd731940-d1ac-4f0a-92b7-080e5965833d.png)
![image](https://user-images.githubusercontent.com/214579/197106372-607d0d12-edb2-4150-89b6-2e471f96cfd1.png)

**Client Versions**
 - 2003 (WoE)
 - Been implemented since forever & ever.

**Comment by MrAntares** [comment]
Note: Map flags are not implemented yet. It needs flags first.

**Comment by alisonrag** [comment]
implemented at:
https://github.com/MrAntares/roBrowserLegacy/commit/5cae8aa360fe5f0389bd6be8677aabdfb093eb7b
