### ISSUE TITLE
Kafra Storage taking out items behavior

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#184]
When in the web browser I take something out of the kafra storage that is further down in the list the storage window always jumps back up to the first item in list (resetting scrolling of storage window). 
This is cumbersome when you want to take out multiple items that are further down in the list. would be great if the storage window would keep its position after the item has been taken out.

**Comment by waken22** [comment]
Cannot replicate it, there's any specific setup to make this happen?

**Comment by MrAntares** [comment]
It was fixed a few commits ago
