### ISSUE TITLE
Friends requests causes all the clients to disconnect.

### ISSUE THREAD

**Issue by KhrysTLords** [MrAntares/roBrowserLegacy#191]
Friends requests causes all the clients to disconnect.

Screenshots 
https://gyazo.com/4198720ef229459ee31b47ba80810b73
https://gyazo.com/3eff51bf0353a18fcd068c2f1bf873ce

Packet/Client version
20150513

Browser/device info
PC Windows/Mac

**Comment by MrAntares** [comment]
Can you also show is the browser console as well when you send the request what packet it sends to the server?
F12/CTRL+SHIFT+I

It's probably a wrong packet since there is no 0x0001 packet for friend stuff.

**Comment by KhrysTLords** [comment]
follows the screenshots

on invite https://gyazo.com/55a93b40d998f3d85967e4b827bc80b6

on accept https://gyazo.com/5fc8c8cc96e14ac22519481d2c1c2b61

server https://gyazo.com/cfb24dd1c90b4de7b2b752aec6018530

packetversions.js
https://gyazo.com/d20ead4215dc526354c6b4febdb1199c

**Comment by KhrysTLords** [comment]
SVN Packetver https://gyazo.com/4fb11b6324e963f253d366707e49cc93
Client Packetver https://gyazo.com/1ad159fb2dc16ae106f4d004e2ed234b

SVN rAthena

**Comment by MrAntares** [comment]
Man this is really strange. Everything checks out 0_o

**Comment by KhrysTLords** [comment]
Should i try in another packetver? will try to downgrade to the previous, and will redo the client Files, just to be sure.
Thank you for all the follow up and support, i will post the result as soon as i test it.

**Comment by Kyatsume** [comment]
check your PACKET.CZ.ACK_REQ_ADD_FRIENDS that sure is the problem

**Comment by MrAntares** [comment]
@KhrysTLords  Is this thing still happening to you? I was unable to reproduce it on the versions i use.

**Comment by alisonrag** [comment]
fixed at:
https://github.com/MrAntares/roBrowserLegacy/commit/1228b3d34daf4f50d5ce1a0120a452e7a7ddc724

**Comment by alisonrag** [comment]
@MrAntares

**Comment by waken22** [comment]
I closed it then ^^
