### ISSUE TITLE
falcon not showing sniper after talking to platinum npc

### ISSUE THREAD

**Issue by jimboy092032** [MrAntares/roBrowserLegacy#193]
**Describe the bug**

**Screenshots (if applicable)**
Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/7947043/222956327-e4f46f48-66f0-41c3-8171-7ffb8e9de18a.png)

**Packet/Client version**
Packet/Client version you use.
20130814

**Browser/device info**
 - Browser: [e.g. stock browser, safari]
Desktop Windows 10/ Chrome
**Additional context**

**Comment by MrAntares** [comment]
Thank you for reporting. It is a known issue. The feature is not implemented yet.
https://github.com/MrAntares/roBrowserLegacy/issues/49
