### ISSUE TITLE
LookTo Implementation

### ISSUE THREAD

**Issue by raiken-mf** [MrAntares/roBrowserLegacy#196]
**Missing feature**
lookTo

**Screenshots (if applicable)**
not needed 

**Client Versions**
 - What client version was it introduced in 
 All?
 - Up to what client version was it live (when was it removed/changed to something else)
 All?

**Packets**
all?

src/Renderer/Entity/Entity.js (Entity.prototype.lookTo)
	 ```
/**
	 * Look at a cell
	 *
	 * @param {number} to_x
	 * @param {number} to_y
	 */
	Entity.prototype.lookTo = function LookTo( to_x, to_y )
	{
		var x = Math.round(to_x-this.position[0]);
		var y = Math.round(to_y-this.position[1]);
		var dir;

		if (x >= 1 ) dir = y >= 1 ? 5 : y === 0 ? 6 : 7;
		if (x === 0) dir = y >= 1 ? 4 : 0;
		if (x <=-1 ) dir = y >= 1 ? 3 : y === 0 ? 2 : 1;

		var prevDirection = this.direction;
		var prevDistance = ((prevDirection - dir + 8) % 8) - 4;
		if (prevDirection == dir) {
			this.headDir = 0;
			this.direction = dir;
		} else {
			if (prevDistance > 0) {
				if (prevDistance == 3 && this.headDir == 1) {
					this.direction = dir;
					this.headDir = 0;
				} else {
					this.direction = (dir - 1 + 8) % 8;
					this.headDir = 1;
				}
			} else if (prevDistance < 0) {
				if (prevDistance == -3 && this.headDir == 2) {
					this.direction = dir;
					this.headDir = 0;
				} else {
					this.direction = (dir + 1 + 8) % 8;
					this.headDir = 2;
				}
			} else if (prevDistance == 0 || prevDistance == 4) {
				this.direction = dir;
				this.headDir = 0;
			} else {
				this.direction = dir;
			}
		}
	};

Maybe some cleanup is needed.
```

**Comment by raiken-mf** [comment]
Also http://forum.robrowser.com/index.php?topic=32240#msg32446 in line 612 of src/Engine/MapEngine.js doesn't exist anymore. I don't know the reason why || KEYS.SHIFT is commented, but it works just fine if I uncomment it on Chrome.

**Comment by MrAntares** [comment]
You mean `src/Renderer/Entity/Entity.js` line 379?
Is this the completion for `// Todo:update head direction`?

I uncomment the shift part in MapEngine.js
I could copy your code, but can you make a fork and make the modification and create a pull request instead? I would like you to get the credit and get labeled as contributor.

**Comment by MrAntares** [comment]
Uncommented the shift check in https://github.com/MrAntares/roBrowserLegacy/commit/2beb54940796f9f870b19ace2f576b3735ba4375

**Comment by raiken-mf** [comment]
Thanks, it would be an honor to get labeled as contributor.
I'll do it tomorrow. Kinda got little time right now cause of work.

**Comment by raiken-mf** [comment]
Created PR with some "cleaner" code in my opinion.
https://github.com/MrAntares/roBrowserLegacy/pull/201

**Comment by raiken-mf** [comment]
PR merged, thanks!
