### ISSUE TITLE
Missing some commands and GM color name

### ISSUE THREAD

**Issue by jimboy092032** [MrAntares/roBrowserLegacy#200]
GAME MASTER COLOR NAME  - color name / Yellow 

/b - command for game mater to broadcast = example /b message
/hide - to hide the game master

**Comment by MrAntares** [comment]
Yeah those are alts for @kami @kamib @hide. You can use these until the slash commands are added

**Comment by jimboy092032** [comment]
Thank you @MrAntares  <3
