### ISSUE TITLE
need off fog /fog for default please

### ISSUE THREAD

**Issue by nusilencer** [MrAntares/roBrowserLegacy#205]
**Describe the issue**
A clear and concise description of what the issue is.

**Screenshots (if applicable)**
Add screenshots to help explain your problem.

**Packet/Client version (if applicable)**
Packet/Client version you use.

**Browser/device info (if applicable)**
 - Browser: [e.g. stock browser, safari]

**Additional context**

**Comment by MrAntares** [comment]
The official setting is on by default, so this can't be considered as an issue. Of yourse you can make your own fork and rewrite the default setting in src/Preferences/Map.js line 25.

**Comment by nusilencer** [comment]
Thank you so much
