### ISSUE TITLE
Song/dance effects break game

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/roBrowserLegacy#230]
Bard/Dancer/Crusader songs break the renderer when 2 or more of them are visible on the screen at once. The whole screen just vanishes. Those effects are needed to be redone anyways, because they are really hacky.

**Comment by MrAntares** [comment]
To be fair each active spell adds 7x7=49 effects to the scene :D In our case 49*2=108 because it shows 2 effects. It is quite bad even if it's just 1 set of effects but with the doubled, broken version it is a disaster

**Comment by waken22** [comment]
I already fixed locally and i know why it's so bad in performance. But the songs requires a lot more of work.

**Comment by waken22** [comment]
A hotfix was applied to this, if for some reason still happens open again the the PR.
