### ISSUE TITLE
Missing 2018+ Basic info UI

### ISSUE THREAD

**Issue by alisonrag** [MrAntares/roBrowserLegacy#232]
**Missing feature**
Missing Last version of basic info UI. Inventory new options was added too. With Favorite tab.

**Screenshots (if applicable)**
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/026b558f-a35e-4562-b9c9-72c4aafcd080)

**Client Versions**
 - 2018+

**Comment by MrAntares** [comment]
Basic info implemented in https://github.com/MrAntares/roBrowserLegacy/commit/bf84e374e515125ac9e2fd27dc03397ae6175ec6
