### ISSUE TITLE
Missing Cursor Update

### ISSUE THREAD

**Issue by alisonrag** [MrAntares/roBrowserLegacy#238]
**Missing feature**
Now it change the ICON when it is on a unwalkable cell

**Screenshots (if applicable)**
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/22279df2-c12a-4859-8192-cf6034f45e2c)

**Client Versions**
2020+ (not sure)

**Comment by waken22** [comment]
Done at https://github.com/MrAntares/roBrowserLegacy/pull/287
