### ISSUE TITLE
Missing Quest Log

### ISSUE THREAD

**Issue by alisonrag** [MrAntares/roBrowserLegacy#239]
**Missing feature**
Please describe the missing feature.

**Screenshots (if applicable)**
OLD:
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/021ccee4-ba51-4420-8edd-61616ab1dc13)

2018+:
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/f8b7d38c-b00f-4306-a87f-ea1d05375edd)

**Client Versions**
2018+

**Packets**
If you know the related packets, please provide them.

**Comment by alisonrag** [comment]
maybe there is a version between these 2 but was not used (idk)

**Comment by MrAntares** [comment]
New UI implemented in
https://github.com/MrAntares/roBrowserLegacy/commit/2e6e0bc604f51c731124fbd3e25b43b44116e734

**Comment by MrAntares** [comment]
Old UI implemented in
https://github.com/MrAntares/roBrowserLegacy/commit/1041e663581136a492ddf9921e2c6324bb49a84c

**Comment by MrAntares** [comment]
I think this is done, right?
