### ISSUE TITLE
[bug] character dont appear at select screen after creation

### ISSUE THREAD

**Issue by alisonrag** [MrAntares/roBrowserLegacy#300]
**Describe the bug**
After Create Char in latest UI the character dont appear, is necessary to relogin

**Screenshots (if applicable)**
https://github.com/MrAntares/roBrowserLegacy/assets/10372732/015df7d8-d823-44f7-9ed7-e3333ee45db3

**Packet/Client version**
20211103

**Browser/device info**
chrome 116.0.5845.188

**Additional context**
no message in console

**Comment by MrAntares** [comment]
The real strange part is that I remember this working... Not sure how it was before this... Maybe the new char was added locally by calling the charselect UI and pushing the new char in the list? :O
