### ISSUE TITLE
Compiling the "Live" server does not copy the src/UI/Components/Intro/images files to the dist/Web

### ISSUE THREAD

**Issue by Filipe-Souza** [MrAntares/roBrowserLegacy#317]
**Describe the bug**
Building the project with ```remoteClient:  ""``` in the tools/builder-web.js file and serving the dist/Web/index.html from a Apache server gives an 404 for the src/UI assets.
This assets should be copied to the dist directory to be served from the dist path.

**Screenshots (if applicable)**
![image](https://github.com/MrAntares/roBrowserLegacy/assets/5497281/e614906a-448c-4feb-bd76-6774d8d80252)

**Packet/Client version**
20180704

**Browser/device info**
 - Browser: Microsoft Edge 120.0.2210.91 
 - Device: Windows 11 22H2

**Additional context**
The dist/Web/index.html is served from a Apache webserver.

**Comment by alisonrag** [comment]
fixed at;
#329
