### ISSUE TITLE
IntroMessage not working anymore.

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#320]
I noticed the feature hasn't been working since early December 2023 and I haven't changed any config.

**Comment by alisonrag** [comment]
if you are talking about this one:
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/16d4b54c-859d-4b95-9541-5cd02ee74aed)

just set `skipIntro:       false,`
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/874b0dd8-3854-4cb6-a74e-3d09de0a4371)

**Comment by alisonrag** [comment]
it is now false by default, because of remoteclient

**Comment by AtomixRO** [comment]
No, I'm talking about this:

												IntroMessage: { path:'IntroMessage/IntroMessage',
												pars: { newsUrl: 'https://classicweb.niktoutro.com/news/news.html' } }
One of the past updates must have broke it and I still have the plugin in my src.

I don't have an image but it's like a pop up that comes before the login screen which was really cool to have.

**Comment by alisonrag** [comment]
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/a93f61d0-396a-4029-9b8c-ef32f46bbc3b)

**Comment by alisonrag** [comment]
go to:
roBrowserLegacy\src\Plugins\IntroMessage\IntroMessage.js

if your packetver is < 2018, set:
`var WinLogin    = require('UI/Components/WinLogin/WinLogin/WinLogin');`

if not:
`var WinLogin    = require('UI/Components/WinLogin/WinLoginV2/WinLoginV2');`

at this moment server is not set yet so its not possible to know the ui version

**Comment by alisonrag** [comment]
i think we can close the issue here and reopen at :
https://github.com/MrAntares/roBrowserLegacy-plugins

my suggestion is add packetver at params

**Comment by AtomixRO** [comment]
Gotcha thanks, I'll open a ticket there.
