### ISSUE TITLE
Cant refine weapons

### ISSUE THREAD

**Issue by GohanDS** [MrAntares/roBrowserLegacy#323]
**Describe the bug**
Cant refine weapons. Cant chose eq to upgrade, is only button close. After close, cant move my character. I have to relog.

**Screenshots (if applicable)**
![image](https://github.com/MrAntares/roBrowserLegacy/assets/3952006/2a7ced4a-5eed-4508-b118-8ca7b5477aee)

**Packet/Client version**
20180314, 20211103

**Browser/device info**
 - Browser: Chrome, Mozilla Firefox

**Additional context**
On ver: 20130618 it works, but cancel of merhants dont wors.

**Comment by Filipe-Souza** [comment]
**Describe the bug**
Same as the [`original`](https://github.com/MrAntares/roBrowserLegacy/issues/323#issue-2088521755), also happens with the Enriched ores NPC

**Screenshots (if applicable)**
![image](https://github.com/MrAntares/roBrowserLegacy/assets/5497281/edb3cd83-37cc-425f-a8d4-29aae70c5603)
![Screenshot 2024-01-18 191610](https://github.com/MrAntares/roBrowserLegacy/assets/5497281/da9e9e62-e205-4e56-b8c8-03fab1e91ea3)

**Packet/Client version**
20211103

**Browser/device info**
 - Browser: Microsoft Edge 120.0.2210.133
 - Device: Win 11 Desktop

**Additional context**
None for now

**Comment by Filipe-Souza** [comment]
@GohanDS If you want to follow up testing the roBrowser, you can configure your emulator (rAthena/HerculesWS) to not use the new UI (implemented in 2016-10-12 and later clients)

Some dialogs from npcs using the close2; function send information to the client asking to close the current dialog but keep running the NPC script on the server, that is why you get stuck (the server is still executing code but the client can't handle it).

Configure your conf/battle/feature.conf file with the: ```feature.refineui: off``` or put this configuration on your conf/import/battle_conf.txt file.

After setting this to off the refine dialog should work:
![image](https://github.com/MrAntares/roBrowserLegacy/assets/5497281/c1881722-45f0-40a2-82aa-eba18c2c6d03)

**Comment by GohanDS** [comment]
It works now. Thank you.
