### ISSUE TITLE
Change Emblem = disconnection

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#338]
**Describe the bug**
Disconnection while trying to change the emblem:
[Warning]: clif_parse: Received packet 0x0153 with expected packet length 2457, but only 2048 bytes remaining, disconnecting session #9.

**Screenshots (if applicable)**
![image](https://github.com/MrAntares/roBrowserLegacy/assets/214579/203662f5-a976-44f4-bcae-32e841c6e80b)

**Packet/Client version**
Packet/Client version 20130618

**Browser/device info**
 - Browser: Any
 - Device: Any

**Comment by alisonrag** [comment]
cant reproduce the issue, are u using the latest version?
as u can see in the following image i changed the emblem 5 times and it worked
can u send the emblem here?
also i'm using the same clientversion

![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/877b13ea-e92b-4899-90c8-32aca4958e81)



![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/b7079f11-7599-4cd9-8bdd-fe7c2ea71684)

**Comment by AtomixRO** [comment]
It does work for me but not for the player who reported this to me and it isn't a cache issue as the player is new and I tested in incognito mode.
I think the player might play on Mac and might use Safari, I'll gather more information about this whenever I see the player online and report here.

**Comment by AtomixRO** [comment]
Found the issue which is if the emblem has a bad format. Client will only trigger this error and not close the client but here browser disconnects the player as the client's behavior can't be reproduced at this stage.

![image](https://github.com/MrAntares/roBrowserLegacy/assets/214579/efd6a9df-8dbb-4ba1-83d7-94d1c2934bde)

**Comment by AtomixRO** [comment]
[test.zip](https://github.com/MrAntares/roBrowserLegacy/files/14235765/test.zip)
You can test with this to reproduce the bug.

**Comment by AtomixRO** [comment]
![image](https://github.com/MrAntares/roBrowserLegacy/assets/214579/f2e49faf-9c8b-4b9f-8025-453e74e84773)
The glitched emblem is because it uses 32 bit depth instead of 24 which then works.

**Comment by MrAntares** [comment]
Nice catch.
I will take a look if we can put in place a check so we don't get error, but really this is user error.
