### ISSUE TITLE
Palettes colors altered between 2020 data.grf & 2024 data.grf

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#351]
**Describe the bug**
Palettes seem to have been altered for most of them as black has replaced most of the usual colors.
Any idea how the main data.grf could have altered these? I haven't seen any error in console either.
Original color appears and then switch to black.

**Screenshots & Video**
2020 data.grf ![image](https://github.com/MrAntares/roBrowserLegacy/assets/214579/b087f06b-36a7-412f-b810-6eed29ec6d73)
2024 02 data.grf 
![image](https://github.com/MrAntares/roBrowserLegacy/assets/214579/c54d18ef-5df1-4d2c-a8c9-94053fd7cb9e)

Video: https://streamable.com/w4oegl

**Packet/Client version**
Any

**Browser/device info**
Any

**Additional context**
DM me to get a link for the 2024 02 data.grf if you need it.

**Comment by MrAntares** [comment]
Is this the same on client?

**Comment by AtomixRO** [comment]
kRO Body sprites were the issue as they've been updated around 2023~.
Fix was the revert them by an older version.
