### ISSUE TITLE
Visible enemy traps on browser-client

### ISSUE THREAD

**Issue by Kuesi** [MrAntares/roBrowserLegacy#354]
**Describe the bug**
You can clearly see orc archer trap

I've noticed that with Magnolia so i believe its with all enemy traps

**Screenshots (if applicable)**
![Screenshot 2024-02-21 151526](https://github.com/MrAntares/roBrowserLegacy/assets/27923606/f78783a4-7bc7-4013-a3ee-3c4d9d050938)

**Packet/Client version**

**Browser/device info**
 - Browser: [e.g. stock browser, safari]

**Additional context**

**Comment by MrAntares** [comment]
Is this still the case if you didn't see the enemy laying the trap?
You should see traps if you see the enemy laying them, only ones that were laid off screen should be invisible.

**Comment by MrAntares** [comment]
On other server (robrowser demos server) is till get isVisible = 1 for monster traps when they appear

**Comment by MrAntares** [comment]
there it is
![image](https://github.com/MrAntares/roBrowserLegacy/assets/5745362/ad5bd201-84ef-4864-a712-7a62092c3693)
Niktout will check the setting on his server, on my server they are always visible

**Comment by MrAntares** [comment]
![image](https://github.com/MrAntares/roBrowserLegacy/assets/5745362/a4a0ca4e-0913-4ef2-ae32-f8e4c1ddac73)
