### ISSUE TITLE
ItemID number above 400000 are "apples"

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#366]
**Describe the issue**
Any ItemID above 400000 are shown as apple even with the correct client side to support them.
By default if an item description is missing, the item is labelled as "unknown item" for any IDs under 400000 yet above it's shown as apple.
**Screenshots (if applicable)**
![image](https://github.com/MrAntares/roBrowserLegacy/assets/214579/248c7c1f-8eee-4c04-9348-ffb9000884b4)

**Packet/Client version (if applicable)**
Any

**Browser/device info (if applicable)**
Any

**Comment by raiken-mf** [comment]
Are you using loadLua: true? I'm also having the same issue.

**Comment by Samuel23** [comment]
couldn't this be related to PACKETVER?

PACKETVER >= 20181121 is where uint32 itemId

before it, uint16 itemId

![image](https://github.com/user-attachments/assets/3c2ccdb8-f394-474a-b474-c802946d71b8)
this item is ItemID 450171

PACKETVER used is 20220406

**Comment by raiken-mf** [comment]
I didn't have exactly the same issue, but kind of a similar one. There was an update to the /src/DB/DBManager.js where the lua file for itemInfo_EN.lua was changed to itemInfo.lub.

Maybe your itemInfo.lub is outdated.

**Comment by AtomixRO** [comment]
Indeed it's related to PACKETVER so a newer is required to display these items.
I'm closing this issue as to solve the issue is to use a newer PACKETVER and make sure your client files are updated to display them properly. I only use TXT for the record and all my files are correct.
