### ISSUE TITLE
Pathing when clicking outside walkable cells

### ISSUE THREAD

**Issue by samtigall** [MrAntares/roBrowserLegacy#390]
**Describe the bug**
Player should navigate to closest cell walkable when clicking on non walkable terrain/outside the map

**Browser/device info**
 - Browser: Chrome
 - Device: Mac/PC

**Additional context**
Examples:
- Moving at Majorous map is a pain.
- In Prontera Castle i used to move the mouse top left and hold the left Mouse Button to walk it through.

**Comment by MrAntares** [comment]
Yup, this is deffo an issue. I had this in mind for years now. Path finding needs to return the last walkable cell at the end of the check and the client should send that as target.
