### ISSUE TITLE
NPC Dialog Number Input oversteps they entry when hitting on enter

### ISSUE THREAD

**Issue by samtigall** [MrAntares/roBrowserLegacy#391]
**Describe the bug**
Number Input gets skipped instantly when using enter in npc dialogs.

**Additional context**
Example: Prontera Smith Phracon Buy Dialog

**Comment by MrAntares** [comment]
I also noticed this, but the reason eludes me. Sometimes this happens, sometimes it works fine. I noticed it on banking npc. Also, this wasn't an issue about a year ago, and I noticed this a few monthy ago.
