### ISSUE TITLE
Item window minimized, can't save maximized.

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#394]
**Describe the bug**
Item Info window is minimized when descriptions are long and when you maximize them, the setting isn't saved when you close the tab and open a new one which used to work a few months ago.
On client item info windows are always maximized.

**Screenshots (if applicable)**
Browser version:
![image](https://github.com/MrAntares/roBrowserLegacy/assets/214579/c0d0d180-84cb-4fef-9396-1bc6eb71abba)

Client version:
![image](https://github.com/MrAntares/roBrowserLegacy/assets/214579/4b980ee8-3488-4ca2-8cc6-136b60321c1c)

Packet/Client version
20130618

Browser/device info
Any

**Comment by andre9x** [comment]
should already be fixed
