### ISSUE TITLE
Missing Switch Equipment UI

### ISSUE THREAD

**Issue by alisonrag** [MrAntares/roBrowserLegacy#404]
**Missing feature**
Missing Switch Equipment UI

**Screenshots (if applicable)**
![image](https://github.com/MrAntares/roBrowserLegacy/assets/10372732/cedd20d8-8d45-45d7-be24-e0ffa59f607d)

**Client Versions**
2017-02-08bRagexeRE or later

**Comment by Samuel23** [comment]
![image](https://github.com/MrAntares/roBrowserLegacy/assets/4675631/45459219-5126-4ec6-bf8b-1d3b0394f9a7)

![image](https://github.com/MrAntares/roBrowserLegacy/assets/4675631/b2a86d5d-fa2b-43f5-bbaf-58da3f946ae4)

Working on this, might take some time :D

**Comment by alisonrag** [comment]
implemented at #417
