### ISSUE TITLE
Right Click triggers windows right click

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#465]
**Describe the bug**
Right Click triggers windows right click on Chrome.

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/94449929-d08e-4c5c-b74a-8cb79495d567)

Packet/Client version
20130618

Browser/device info
Chrome so far, works fine on Firefox.

**Comment by Sehrentos** [comment]
This can probably relate to this? https://github.com/MrAntares/roBrowserLegacy/pull/476
I had same kind of issue, where Equipment.getUI().isInEquipList() method call resulted an error and contextmenu opened.

**Comment by alisonrag** [comment]
fixed at #477
