### ISSUE TITLE
Hand cursor sprite on Vending Box gone

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#467]
**Describe the bug**
Hand cursor sprite on Vending Box gone, we now get the plain windows cursor.

**Screenshots (if applicable)**
Client:
![image](https://github.com/user-attachments/assets/82c22972-3887-4536-8361-6a1c4da373cf)

Also the RO spinning cursor has been gone for a long time or was it ever used before?
https://github.com/user-attachments/assets/ebf69d44-d208-4134-924e-71e0e39bf509

Packet/Client version
20130618

Browser/device info
Any

**Comment by MrAntares** [comment]
Yes, both cursors are used. There is a setting in the options menu to to show official cursors or not. Didn't you remove that tick?

**Comment by AtomixRO** [comment]
It's working as intended by default now. Closing this issue.
