### ISSUE TITLE
Map textures loading error after 100% loading on map change.

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#473]
**Describe the bug**
It seems that textures can't be loaded at random times while loading a map, the browser gets stuck on loading 100% and this happened bug has been introduced between early June to present days.

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/a966c032-0c25-41c2-8c11-577debe19f3a)

Packet/Client version
20130618

Browser/device info
Any

**Comment by Samuel23** [comment]
this seems related to this: https://github.com/MrAntares/roBrowserLegacy/pull/460

can I have more info to reproduce this?

**Comment by AtomixRO** [comment]
@Samuel23 Unfortunately it's completely random, it can occur for some players and not others even when they go to the same map.
This particular log is from a player that gets affected quite often while others don't, that's the maximum information I got at this stage.

**Comment by Samuel23** [comment]
maybe this is related to character select? i remember @Boblee-D-Dev mentioning to me in pm where he encountered an error with damage when changing character, but i was not able to reproduce it as well.

**Comment by AtomixRO** [comment]
Got another log from a player:
![image](https://github.com/user-attachments/assets/4359f24d-c0c5-4512-ab12-992d63d674d2)

**Comment by AtomixRO** [comment]
> > this seems related to this: #460
> > can I have more info to reproduce this?
> 
> I think it happens when a damage number is visible when changing map.

If that's the case then it may also be damage that isn't visible "on your screen" while loading a map coming from a map like a town where there is no damage if this makes sense.

**Comment by Sehrentos** [comment]
Possibly same issue happended here, after death loading screen got stuck:
![image](https://github.com/user-attachments/assets/e205a987-5057-4fb4-83db-1fbd4027f8a6)

**Comment by Sehrentos** [comment]
Yeap i think your right. In the It seems WebGL Context is set to null in the Effects/Damage.js and in MemoryManager.js it's trying to access it's method isTexture, but failes. Possible null check can fix this?

**Comment by alisonrag** [comment]
fixed at #478
