### ISSUE TITLE
Status window can't be displayed on 20151104

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#484]
**Describe the bug**
Status window can't be displayed

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/51c7c0ea-2b12-4f6e-95fc-8875c7107e52)

**Packet/Client version**
20151104

**Browser/device info**
 - Any

**Comment by MrAntares** [comment]
I think it is related to
https://github.com/MrAntares/roBrowserLegacy/commit/0148a510340e3e26085880644eec4a7bde40d934
@Samuel23 Can you help us in this?

**Comment by MrAntares** [comment]
The Equipment win toggles weren't updated, and this wond't work, unless you have only one server that's version falls into this range:
![image](https://github.com/user-attachments/assets/84fd7c5f-61d6-47e0-923d-d58f8b77d12c)

**Comment by MrAntares** [comment]
This require is only executed on script initialization and not when changing servers/ui versions.

**Comment by MrAntares** [comment]
As a temporary solution I added ALT + A as a static command. This might cause some more issues than it solves, but the real solution would be a dynamic shortcut list and key config window..

**Comment by MrAntares** [comment]
Fixed in https://github.com/MrAntares/roBrowserLegacy/commit/c485e14051b30bffad6f236578a8f97036f95549
