### ISSUE TITLE
Damage done to monsters from other players is seen in seen in your own chat box.

### ISSUE THREAD

**Issue by AtomixRO** [MrAntares/roBrowserLegacy#490]
**Describe the bug**
Damage done to monsters from other players is seen in seen in your own chat box.
No party/no guild.

**Screenshots (if applicable)**
![image](https://github.com/user-attachments/assets/6cf08d54-accb-488a-bdea-e8706f475bd2)

**Packet/Client version**
20130618 (could be any?)

**Browser/device info**
 - Any

**Comment by MrAntares** [comment]
Probably the result of that currently we only check if the src AID is the same as the player, then we show log as you dealt the damage and every other case is handled like it was dealt to the player. Need to check if either the src or the target is the player and show the messages accordingly.
Aside from this fix we could add a custom filter option to show other player's damage as well in the log with correct src and target names...

**Comment by AtomixRO** [comment]
I also noticed you don't see the damage dealt to mob anymore which is wrong.

![image](https://github.com/user-attachments/assets/eea1f613-d4b7-48cd-af2d-7bba9f1bc149)
