### ISSUE TITLE
disable skill name display Blitz Beat

### ISSUE THREAD

**Issue by nusilencer** [MrAntares/roBrowserLegacy#495]
how to disable skill name display Blitz Beat 
When Passive Skill Steel Crow  is activated
![blitz](https://github.com/user-attachments/assets/4f48b07a-951a-45ff-9868-29b34a9eaefa)

**Comment by MrAntares** [comment]
Officially it is displayed since it is an autocast of blitz beat and it is part of the skill itself not steel crow.

You can sourcemod it in
https://github.com/MrAntares/roBrowserLegacy/blob/master/src/Engine/MapEngine/Entity.js#L61

Add the skill name to the SkillNameDisplayExclude, but this will also hide blitz beat when used normally.

**Comment by MrAntares** [comment]
Hmm I just saw a newer video where it is hidden when auto blitzing. Not sure if they changed it or if it was always like this but really strange. Maybe autocasts don't show name?

**Comment by MrAntares** [comment]
Here it shows skill name:
https://www.youtube.com/watch?v=WohbTbE8G0o
Here it doesn't:
https://www.youtube.com/watch?v=H4zZttQ8IDg

Was this a renewal change?

**Comment by MrAntares** [comment]
Here autocasts showing but not blitz beat and is pre-re:
https://www.youtube.com/watch?v=8L2aiLJ-_Aw

I am confuzed what to do :D

**Comment by nusilencer** [comment]
> Hmm I just saw a newer video where it is hidden when auto blitzing. Not sure if they changed it or if it was always like this but really strange. Maybe autocasts don't show name?

when auto Blitz Beat 
Name will not be displayed. :)

**Comment by Sehrentos** [comment]
I think this could be an option to opt in or out. Some might even want the passive skill trigger to show spell name being triggered?

**Comment by MrAntares** [comment]
Passive skills never show since they don't send a skill packet

**Comment by AtomixRO** [comment]
![image](https://github.com/user-attachments/assets/a14737aa-0c6b-470c-9c35-39a3f7222535)

Doesn't display on Packet/Client version 20130618

**Comment by MrAntares** [comment]
@AtomixRO you mean the double attack?

**Comment by MrAntares** [comment]
Passive skills don't perform a skill attack.
https://irowiki.org/classic/Steel_Crow
![image](https://github.com/user-attachments/assets/65066137-e738-459d-ae51-1a9ba3094fb6)

Blitz Beat itself has a secondarry effect that triggers auto blitz:
https://irowiki.org/classic/Blitz_Beat
![image](https://github.com/user-attachments/assets/75178529-24eb-4433-9199-7151c1dedc94)

Auto blitz is performed by the server sending an autoskill packet that initiates a normal blitz beat. From the client's perspective there is no difference between manually starting the blitz or auto triggering it, in the end both uses the same skill packet. That is why I have no idea how to tell them apart. At this point I can either disable both manual and auto blitz skill name or show them both. I have no idea how official client deals with this.

**Comment by MrAntares** [comment]
Here is the packet for Manual blitz:
![image](https://github.com/user-attachments/assets/c21a446e-3ee5-43b9-91ca-5811f0b11644)
Here is Auto blitz:
![image](https://github.com/user-attachments/assets/5d79e8b4-6d9c-4653-90ff-85b38816bc63)
The only difference I see is the skill level. I can add a condition so it doesn't display skillname if level is -1, but this is a pretty lame and hacky way and will also affect any other skill as well. Meh. K then. I do this when i have some time.
