### ISSUE TITLE
Stat distribution on char create

### ISSUE THREAD

**Issue by MrAntares** [MrAntares/roBrowserLegacy#93]
When creating a character the statuses are not distributed after entering the game.

**Comment by MrAntares** [comment]
Found out this is actually working as intended. After 2012-03-10 the character creation window no longer has a stat distribution, only name and hair and you can distribute all the stats in the game itself. The new char create UI needs to be implemented.

**Comment by alisonrag** [comment]
@MrAntares 
is all version implemented? i think yes

**Comment by MrAntares** [comment]
Yes
